matrix:
  - name: Markdown
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
            - a
    sources:
      - "**/*.md"
    default_encoding: utf-8
