name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: rojopolis/spellcheck-github-actions@0.35.0
        name: Spellcheck
        with:
          config_path: .github/spellcheck-config.yml
          task_name: Markdown
